#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Connection tracking index for friTap sessions.

Consolidates the scattered sets from the legacy SSL_Logger (keydump_Set,
traced_Socket_Set, traced_scapy_socket_Set) into a single
session-scoped tracker.
"""

from __future__ import annotations
import threading
from dataclasses import dataclass
from typing import Dict, Optional, Set, Tuple


# Hex prefix of the dummy session ID generated by the friTap agent
# (see DUMMY_SESSION_ID_* constants in agent/tls/definitions/shared_constants.ts).
# Connections with session IDs starting with this value lack a real TLS
# session ID and should be matched via client_random instead.
DUMMY_SESSION_ID_BASE = "59FD71B7B90202F359D89E66AE4E61247954E28431F6C6AC46625D472FF7633"

# NSS-specific dummy session ID returned when SSL layer lookup fails.
NSS_DUMMY_SESSION_ID = "3E8ABF58649A1A1C58824D704173BA9AAFA2DA33B45FFEA341D218B29BBACF8F"


def normalize_4tuple(src_addr: str, src_port: int,
                     dst_addr: str, dst_port: int) -> str:
    """Return a canonical endpoint pair — perspective-independent.

    Sorts the two endpoints lexicographically so that the same physical
    connection produces the same key regardless of which side reports it.
    """
    ep1 = f"{src_addr}:{src_port}"
    ep2 = f"{dst_addr}:{dst_port}"
    lo, hi = (ep1, ep2) if ep1 < ep2 else (ep2, ep1)
    return f"{lo}-{hi}"


def resolve_connection_key(
    src_addr: str,
    src_port: int,
    dst_addr: str,
    dst_port: int,
    session_token: str = "",
    client_random: str = "",
    protocol: str = "tls",
) -> str:
    """Deterministic connection key with tiered fallback.

    Tier 1: client_random — unique per TLS connection (not reused across resumption)
    Tier 2: protocol-specific session token (ssl_session_id, SSH session_id, etc.)
    Tier 3: normalized 4-tuple (perspective-independent, works for any protocol)

    The ``cr:`` / ``sid:`` / ``net:`` prefixes prevent cross-tier key collisions.
    """
    if client_random:
        return f"cr:{protocol}:{client_random}"
    if session_token and not session_token.startswith(DUMMY_SESSION_ID_BASE) and session_token != NSS_DUMMY_SESSION_ID:
        return f"sid:{protocol}:{session_token}"
    return f"net:{normalize_4tuple(src_addr, src_port, dst_addr, dst_port)}"


@dataclass
class ConnectionInfo:
    """Metadata for a tracked connection."""
    src_addr: str = ""
    src_port: int = 0
    dst_addr: str = ""
    dst_port: int = 0
    ss_family: str = "AF_INET"
    ssl_session_id: str = ""
    protocol: str = "tls"
    bytes_read: int = 0
    bytes_written: int = 0


class ConnectionIndex:
    """Session-scoped connection and key deduplication tracker.

    Thread-safe. Created per-session, destroyed when session ends.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._seen_keys: Set[str] = set()
        self._traced_sockets: Set[Tuple[str, int, str, int]] = set()
        self._connections: Dict[str, ConnectionInfo] = {}
        self._client_random_map: Dict[str, str] = {}

    def is_new_key(self, key_data: str) -> bool:
        """Check if key material is new (not seen before). Thread-safe."""
        with self._lock:
            if key_data in self._seen_keys:
                return False
            self._seen_keys.add(key_data)
            return True

    def is_new_socket(self, src_addr: str, src_port: int,
                       dst_addr: str, dst_port: int) -> bool:
        """Check if a socket tuple is new. Thread-safe."""
        key = (src_addr, src_port, dst_addr, dst_port)
        with self._lock:
            if key in self._traced_sockets:
                return False
            self._traced_sockets.add(key)
            return True

    def get_or_create_connection(
        self,
        src_addr: str,
        src_port: int,
        dst_addr: str,
        dst_port: int,
        **kwargs,
    ) -> Tuple[str, ConnectionInfo]:
        """Get existing or create new connection entry.

        Returns (connection_id, connection_info).
        Uses a composite key including ssl_session_id when a real
        (non-dummy) session ID is available, allowing disambiguation
        of multiplexed connections on the same socket tuple.
        """
        ssl_session_id = kwargs.get("ssl_session_id", "")
        base_key = f"{src_addr}:{src_port}-{dst_addr}:{dst_port}"
        # Use composite key when we have a real (non-dummy) session ID
        if ssl_session_id and not ssl_session_id.startswith(DUMMY_SESSION_ID_BASE) and ssl_session_id != NSS_DUMMY_SESSION_ID:
            key = f"{base_key}:{ssl_session_id}"
        else:
            key = base_key
        with self._lock:
            if key not in self._connections:
                self._connections[key] = ConnectionInfo(
                    src_addr=src_addr,
                    src_port=src_port,
                    dst_addr=dst_addr,
                    dst_port=dst_port,
                    **kwargs,
                )
            return key, self._connections[key]

    def register_client_random(self, client_random: str, connection_id: str) -> None:
        """Associate a client_random hex string with a connection_id.

        Thread-safe. Silently ignores empty *client_random* values.
        """
        if not client_random:
            return
        with self._lock:
            self._client_random_map[client_random] = connection_id

    def get_connection_by_client_random(self, client_random: str) -> Optional[str]:
        """Look up a connection_id by its client_random hex string.

        Returns the connection_id or ``None`` if not found. Thread-safe.
        """
        if not client_random:
            return None
        with self._lock:
            return self._client_random_map.get(client_random)

    @property
    def key_count(self) -> int:
        """Number of unique keys seen."""
        with self._lock:
            return len(self._seen_keys)

    @property
    def connection_count(self) -> int:
        """Number of tracked connections."""
        with self._lock:
            return len(self._connections)

    @property
    def socket_count(self) -> int:
        """Number of traced sockets."""
        with self._lock:
            return len(self._traced_sockets)

    def remove_connection(self, connection_id: str) -> None:
        """Remove a connection and its associated client_random mapping.

        Thread-safe. Silently ignores unknown *connection_id* values.
        """
        with self._lock:
            self._connections.pop(connection_id, None)
            # Prune client_random entries that pointed to this connection
            stale = [cr for cr, cid in self._client_random_map.items()
                     if cid == connection_id]
            for cr in stale:
                del self._client_random_map[cr]

    def clear(self) -> None:
        """Clear all tracking state."""
        with self._lock:
            self._seen_keys.clear()
            self._traced_sockets.clear()
            self._connections.clear()
            self._client_random_map.clear()
