// Auto-generated from Python source-of-truth modules.
// Do NOT edit by hand. Run: python dev/generate_agent_types.py
//
// Generated by: dev/generate_agent_types.py

export const DUMMY_SESSION_ID_BASE = "59FD71B7B90202F359D89E66AE4E61247954E28431F6C6AC46625D472FF7633";
export const INFRASTRUCTURE_PORTS = new Set([5037, 5555, 27042, 27043]) as ReadonlySet<number>;
export const AGENT_ABI_VERSION = 1;
