#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generate TypeScript interfaces from Pydantic agent message schemas.

Reads friTap/schemas/agent_messages.py and outputs agent/schemas/messages.ts
with TypeScript interfaces and type guard functions.

Usage:
    python dev/generate_agent_types.py           # Generate
    python dev/generate_agent_types.py --check   # Verify up-to-date
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path
from typing import Any, Literal, Union, get_args, get_origin

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from friTap.schemas.agent_messages import (  # noqa: E402
    ConsoleMessage,
    ConsoleDevMessage,
    ConsoleDebugMessage,
    ConsoleInfoMessage,
    ConsoleWarnMessage,
    ConsoleErrorMessage,
    DatalogMessage,
    IPSecChildSAKeysMessage,
    IPSecIKEKeysMessage,
    KeylogMessage,
    LibraryDetectedMessage,
    NetlogMessage,
    SSHNewKeysMessage,
    SSHKeyMessage,
)

OUTPUT_PATH = PROJECT_ROOT / "agent" / "schemas" / "messages.ts"

HEADER = """\
// Auto-generated from friTap/schemas/agent_messages.py
// Do NOT edit by hand. Run: python dev/generate_agent_types.py
//
// Generated by: dev/generate_agent_types.py

"""

# Map Python types to TypeScript types
TYPE_MAP: dict[type, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
    bytes: "ArrayBuffer",
}


def python_type_to_ts(annotation: Any) -> str:
    """Convert a Python type annotation to a TypeScript type string."""
    if annotation is type(None):
        return "null"

    origin = get_origin(annotation)

    # Handle Literal types
    if origin is type(None):
        return "null"

    # Check for Literal
    if origin is Literal:
        args = get_args(annotation)
        return " | ".join(f'"{a}"' if isinstance(a, str) else str(a) for a in args)

    # Handle Union (int | str, Optional, etc.)
    if origin is Union:
        args = get_args(annotation)
        ts_types = [python_type_to_ts(a) for a in args]
        return " | ".join(ts_types)

    # Handle basic types
    if annotation in TYPE_MAP:
        return TYPE_MAP[annotation]

    # Handle dict
    if origin is dict:
        key_type, val_type = get_args(annotation)
        return f"Record<{python_type_to_ts(key_type)}, {python_type_to_ts(val_type)}>"

    # Handle list
    if origin is list:
        (item_type,) = get_args(annotation)
        return f"{python_type_to_ts(item_type)}[]"

    # Fallback
    return "any"


def generate_interface(model_class: type) -> str:
    """Generate a TypeScript interface from a Pydantic model."""
    lines = [f"export interface {model_class.__name__} {{"]

    schema = model_class.model_json_schema()
    required = set(schema.get("required", []))

    for field_name, field_info in model_class.model_fields.items():
        ts_type = python_type_to_ts(field_info.annotation)
        optional = "" if field_name in required or field_name == "contentType" else "?"
        lines.append(f"    {field_name}{optional}: {ts_type};")

    lines.append("}")
    return "\n".join(lines)


def generate_type_guard(model_class: type) -> str:
    """Generate a TypeScript type guard function."""
    name = model_class.__name__

    # Find the contentType literal value
    content_type_field = model_class.model_fields.get("contentType")
    if content_type_field is None:
        return ""

    annotation = content_type_field.annotation
    args = get_args(annotation)

    if len(args) == 1:
        check = f'(msg as any)?.contentType === "{args[0]}"'
    else:
        values = ", ".join(f'"{a}"' for a in args)
        check = f"[{values}].includes((msg as any)?.contentType)"

    return textwrap.dedent(f"""\
        export function is{name}(msg: unknown): msg is {name} {{
            return {check};
        }}""")


def generate_union_type(models: list[type]) -> str:
    """Generate the AgentMessage union type."""
    names = [m.__name__ for m in models]
    return "export type AgentMessage = " + "\n    | ".join(names) + ";\n"


def generate_all() -> str:
    """Generate the complete TypeScript file content."""
    models = [
        KeylogMessage,
        DatalogMessage,
        LibraryDetectedMessage,
        ConsoleMessage,
        ConsoleDevMessage,
        ConsoleDebugMessage,
        ConsoleInfoMessage,
        ConsoleWarnMessage,
        ConsoleErrorMessage,
        NetlogMessage,
        SSHNewKeysMessage,
        SSHKeyMessage,
        IPSecChildSAKeysMessage,
        IPSecIKEKeysMessage,
    ]

    parts = [HEADER]

    for model in models:
        parts.append(generate_interface(model))
        parts.append("")
        guard = generate_type_guard(model)
        if guard:
            parts.append(guard)
            parts.append("")

    parts.append(generate_union_type(models))

    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate TS types from Pydantic schemas")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated file is up-to-date (for CI)",
    )
    args = parser.parse_args()

    generated = generate_all()

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"ERROR: {OUTPUT_PATH} does not exist. Run without --check first.")
            sys.exit(1)
        existing = OUTPUT_PATH.read_text()
        if existing != generated:
            print(f"ERROR: {OUTPUT_PATH} is out of date. Run: python dev/generate_agent_types.py")
            sys.exit(1)
        print("OK: Generated types are up-to-date.")
        sys.exit(0)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated)
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
