#!/usr/bin/env python3
"""Generate a standalone Python script for using friTap's Frida agent directly.

Usage examples:

    # Minimal: generates script that loads agent from file
    python dev/generate_standalone.py -o my_script.py

    # Single-file: embed both agent JS and default patterns
    python dev/generate_standalone.py --embed-agent --embed-patterns -o my_script.py

    # Desktop target with SSH protocol
    python dev/generate_standalone.py --platform desktop --protocol ssh --target myapp -o my_script.py
"""

import argparse
import json
import os
import sys
import textwrap

# Project root is one level up from dev/
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

AGENT_JS_PATH = os.path.join(PROJECT_ROOT, "friTap", "fritap_agent.js")
PATTERNS_JSON_PATH = os.path.join(PROJECT_ROOT, "friTap", "patterns", "default_patterns.json")


def build_script(
    embed_agent: bool,
    embed_patterns: bool,
    target: str,
    platform: str,
    protocol: str,
) -> str:
    """Build the standalone Python source as a string."""

    # Read agent JS if embedding
    agent_js_literal = "None"
    if embed_agent:
        if not os.path.isfile(AGENT_JS_PATH):
            print(
                f"Error: Agent JS not found at {AGENT_JS_PATH}\n"
                "Run: frida-compile agent/fritap_agent.ts -o friTap/fritap_agent.js",
                file=sys.stderr,
            )
            sys.exit(1)
        with open(AGENT_JS_PATH, "r", encoding="utf-8") as f:
            agent_js_content = f.read()
        # Use a raw triple-quoted string to avoid escaping issues
        agent_js_literal = 'r"""\n' + agent_js_content + '\n"""'

    # Read patterns JSON if embedding
    patterns_literal = "None"
    if embed_patterns:
        if not os.path.isfile(PATTERNS_JSON_PATH):
            print(
                f"Error: Patterns file not found at {PATTERNS_JSON_PATH}",
                file=sys.stderr,
            )
            sys.exit(1)
        with open(PATTERNS_JSON_PATH, "r", encoding="utf-8") as f:
            patterns_dict = json.load(f)
        # The config_batch expects a JSON *string*, so we embed the serialized form
        patterns_literal = repr(json.dumps(patterns_dict))

    mobile_default = "True" if platform == "mobile" else "False"

    # Build the config section with substituted values.
    # NOTE: We assemble lines manually instead of using textwrap.dedent with
    # an f-string because embedded multi-line literals (agent JS) break dedent.
    config_lines = [
        f"TARGET = {target!r}",
        f"MOBILE = {mobile_default}",
        f"PROTOCOL = {protocol!r}",
        "",
        "# Agent JavaScript source.",
        "# When None, the script reads from AGENT_JS_FILE instead.",
        f"EMBEDDED_AGENT_JS = {agent_js_literal}",
        "",
        '# Path to the agent JS file (used when EMBEDDED_AGENT_JS is None)',
        'AGENT_JS_FILE = "friTap/fritap_agent.js"',
        "",
        "# Patterns JSON string for the config_batch handshake.",
        "# When None, the agent uses its built-in defaults.",
        f"PATTERNS = {patterns_literal}",
        "",
        "# Offsets JSON string (None = no custom offsets)",
        "OFFSETS = None",
        "",
        "# Feature flags",
        "SOCKET_TRACING = False",
        "DEFAULT_FD = False",
        "EXPERIMENTAL = False",
        "INSTALL_LSASS_HOOK = True",
        "USE_MODERN = False",
        "ANTI_ROOT = False",
        "",
        "# Keylog output file (None = print to stdout)",
        "KEYLOG_FILE = None",
    ]
    config_block = "\n".join(config_lines) + "\n"

    # The rest of the script is static - no substitution needed
    header = textwrap.dedent('''\
        #!/usr/bin/env python3
        """Standalone friTap capture script.

        Generated by dev/generate_standalone.py.
        Uses friTap's Frida agent directly without the friTap Python package.

        Usage:
            python <this_script> [TARGET] [--spawn] [-D DEVICE]
        """

        import argparse
        import json
        import os
        import struct
        import sys
        import time
        import threading

        try:
            import frida
        except ImportError:
            print("Error: 'frida' package is required. Install with: pip install frida", file=sys.stderr)
            sys.exit(1)

        # ---------------------------------------------------------------------------
        # Configuration constants  (edit these or override via CLI args)
        # ---------------------------------------------------------------------------

    ''')

    body = textwrap.dedent('''\
        # ---------------------------------------------------------------------------
        # Message handler
        # ---------------------------------------------------------------------------

        startup_done = threading.Event()
        running = True
        keylog_fh = None


        def on_message(message, data):
            """Handle messages from the friTap Frida agent."""
            global running

            msg_type = message.get("type")

            if msg_type == "error":
                desc = message.get("description", "")
                stack = message.get("stack", "")
                print(f"[agent error] {desc}", file=sys.stderr)
                if stack:
                    print(stack, file=sys.stderr)
                return

            if msg_type != "send":
                return

            payload = message.get("payload")

            # --- Startup handshake ---
            if isinstance(payload, str):
                handle_handshake(payload)
                return

            if not isinstance(payload, dict):
                return

            content_type = payload.get("contentType")
            if content_type is None:
                return

            # --- Keylog (TLS key material) ---
            if content_type == "keylog":
                keylog_line = payload.get("keylog", "")
                if keylog_line:
                    if keylog_fh:
                        keylog_fh.write(keylog_line + "\\n")
                        keylog_fh.flush()
                    else:
                        print(keylog_line)

            # --- Datalog (plaintext read/write) ---
            elif content_type in ("datalog", "datalog_read", "datalog_write"):
                func = payload.get("function", "?")
                src = payload.get("src_addr", "?")
                dst = payload.get("dst_addr", "?")
                src_port = payload.get("src_port", "?")
                dst_port = payload.get("dst_port", "?")
                length = len(data) if data else 0
                print(f"[{func}] {src}:{src_port} -> {dst}:{dst_port} ({length} bytes)")

            # --- SSH keys ---
            elif content_type == "ssh_keys":
                print(f"[SSH] {payload}")

            # --- IPSec keys ---
            elif content_type == "ipsec_keys":
                print(f"[IPSec] {payload}")

            # --- Console output from agent ---
            elif content_type == "console":
                print(f"[agent] {payload.get('console', '')}")
            elif content_type == "console_dev":
                print(f"[agent/dev] {payload.get('console_dev', '')}", file=sys.stderr)
            elif content_type == "console_error":
                print(f"[agent/error] {payload.get('console_error', '')}", file=sys.stderr)
            elif content_type == "console_warn":
                print(f"[agent/warn] {payload.get('console_warn', '')}", file=sys.stderr)
            elif content_type == "console_info":
                print(f"[agent/info] {payload.get('console_info', '')}")
            elif content_type == "console_debug":
                print(f"[agent/debug] {payload.get('console_debug', '')}", file=sys.stderr)

            # --- Library detection ---
            elif content_type == "library_detected":
                lib_name = payload.get("library", "unknown")
                print(f"[+] Detected TLS library: {lib_name}")


        def handle_handshake(payload):
            """Respond to agent startup handshake messages."""
            global script_handle

            if payload == "config_batch":
                batch = {
                    "offsets": OFFSETS,
                    "patterns": PATTERNS,
                    "socket_tracing": SOCKET_TRACING,
                    "defaultFD": DEFAULT_FD,
                    "experimental": EXPERIMENTAL,
                    "protocol_select": PROTOCOL,
                    "install_lsass_hook": INSTALL_LSASS_HOOK,
                    "use_modern": USE_MODERN,
                    "library_scan": None,
                }
                script_handle.post({"type": "config_batch", "payload": batch})
                return

            if payload == "anti":
                script_handle.post({"type": "antiroot", "payload": ANTI_ROOT})
                startup_done.set()
                return

            # Legacy individual handshake fallback (older agent builds)
            legacy_map = {
                "offsets": ("offsets", OFFSETS),
                "patterns": ("patterns", PATTERNS),
                "socket_trace": ("socket_trace", SOCKET_TRACING),
                "defaultFD": ("defaultFD", DEFAULT_FD),
                "experimental": ("experimental", EXPERIMENTAL),
                "protocol_select": ("protocol_select", PROTOCOL),
                "install_lsass_hook": ("install_lsass_hook", INSTALL_LSASS_HOOK),
                "use_modern": ("use_modern", USE_MODERN),
            }
            if payload in legacy_map:
                msg_type_key, value = legacy_map[payload]
                script_handle.post({"type": msg_type_key, "payload": value})

        # ---------------------------------------------------------------------------
        # Main
        # ---------------------------------------------------------------------------

        script_handle = None


        def main():
            global script_handle, running, keylog_fh

            parser = argparse.ArgumentParser(
                description="Standalone friTap capture script"
            )
            parser.add_argument(
                "target",
                nargs="?",
                default=TARGET,
                help=f"Target process name or PID (default: {TARGET})",
            )
            parser.add_argument(
                "--spawn", "-s",
                action="store_true",
                default=False,
                help="Spawn the target process instead of attaching",
            )
            parser.add_argument(
                "-D", "--device",
                default=None,
                help="Frida device ID (default: USB for mobile, local for desktop)",
            )
            parser.add_argument(
                "--retries",
                type=int,
                default=3,
                help="Number of attach retries (default: 3)",
            )
            parser.add_argument(
                "--keylog", "-k",
                default=KEYLOG_FILE,
                help="Write TLS key log to this file (default: stdout)",
            )
            args = parser.parse_args()

            # Open keylog file if requested
            if args.keylog:
                keylog_fh = open(args.keylog, "a", encoding="utf-8")
                print(f"[*] Writing keylog to {args.keylog}")

            # Load the agent JavaScript
            if EMBEDDED_AGENT_JS is not None:
                agent_source = EMBEDDED_AGENT_JS
            else:
                agent_path = os.path.abspath(AGENT_JS_FILE)
                if not os.path.isfile(agent_path):
                    print(f"Error: Agent JS not found at {agent_path}", file=sys.stderr)
                    sys.exit(1)
                with open(agent_path, "r", encoding="utf-8") as f:
                    agent_source = f.read()

            # Connect to device
            if args.device:
                device = frida.get_device(args.device)
            elif MOBILE:
                device = frida.get_usb_device()
            else:
                device = frida.get_local_device()

            print(f"[*] Device: {device.name}")
            print(f"[*] Target: {args.target} ({'spawn' if args.spawn else 'attach'})")
            print(f"[*] Protocol: {PROTOCOL}")

            # Attach or spawn
            session = None
            for attempt in range(1, args.retries + 1):
                try:
                    if args.spawn:
                        pid = device.spawn([args.target])
                        session = device.attach(pid)
                    else:
                        session = device.attach(args.target)
                    break
                except frida.ProcessNotFoundError:
                    if attempt < args.retries:
                        print(f"[*] Process not found, retrying ({attempt}/{args.retries})...")
                        time.sleep(1)
                    else:
                        print(f"Error: Process '{args.target}' not found after {args.retries} attempts", file=sys.stderr)
                        sys.exit(1)
                except frida.ServerNotRunningError:
                    print("Error: Frida server is not running on the target device", file=sys.stderr)
                    sys.exit(1)

            # Create and load the script
            script_handle = session.create_script(agent_source)
            script_handle.on("message", on_message)
            script_handle.load()

            if args.spawn:
                device.resume(pid)
                print(f"[*] Spawned and resumed PID {pid}")

            # Wait for handshake to complete
            if not startup_done.wait(timeout=10):
                print("[!] Warning: Agent handshake did not complete within 10 seconds", file=sys.stderr)

            print("[*] Capturing... Press Ctrl+C to stop.")

            try:
                while running:
                    time.sleep(0.5)
            except KeyboardInterrupt:
                print("\\n[*] Stopping...")
            finally:
                running = False
                try:
                    session.detach()
                except Exception:
                    pass
                if keylog_fh:
                    keylog_fh.close()
                print("[*] Done.")


        if __name__ == "__main__":
            main()
    ''')

    return header + config_block + "\n" + body


def main():
    parser = argparse.ArgumentParser(
        description="Generate a standalone Python script for using friTap's Frida agent directly.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples:
              %(prog)s -o my_script.py
              %(prog)s --embed-agent --embed-patterns -o standalone.py
              %(prog)s --platform desktop --protocol ssh --target myapp -o ssh_capture.py
        """),
    )
    parser.add_argument(
        "-o", "--output",
        required=True,
        help="Output file path (required)",
    )
    parser.add_argument(
        "--embed-agent",
        action="store_true",
        default=False,
        help="Embed friTap/fritap_agent.js inline as a string literal",
    )
    parser.add_argument(
        "--embed-patterns",
        action="store_true",
        default=False,
        help="Embed friTap/patterns/default_patterns.json as the patterns config value",
    )
    parser.add_argument(
        "--target",
        default="com.android.chrome",
        help="Default target app name (default: com.android.chrome)",
    )
    parser.add_argument(
        "--platform",
        choices=["desktop", "mobile"],
        default="mobile",
        help="Device selection mode (default: mobile)",
    )
    parser.add_argument(
        "--protocol",
        choices=["tls", "ssh", "ipsec"],
        default="tls",
        help="Protocol to capture (default: tls)",
    )
    args = parser.parse_args()

    source = build_script(
        embed_agent=args.embed_agent,
        embed_patterns=args.embed_patterns,
        target=args.target,
        platform=args.platform,
        protocol=args.protocol,
    )

    output_path = os.path.abspath(args.output)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(source)

    # Make executable
    os.chmod(output_path, 0o755)

    print(f"Generated: {output_path}")
    print(f"  Target:    {args.target}")
    print(f"  Platform:  {args.platform}")
    print(f"  Protocol:  {args.protocol}")
    print(f"  Agent:     {'embedded' if args.embed_agent else 'loaded from file'}")
    print(f"  Patterns:  {'embedded' if args.embed_patterns else 'none (agent defaults)'}")


if __name__ == "__main__":
    main()
