#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Name-free reveal-token denylist: generator + scanner (friTap tiering §F L1).

The public repo must never *enumerate* the private reveal-tokens, yet the leak
guard must still detect them. Resolution (the "denylist-as-leak paradox"): hash
the tokens. ``scripts/denylist.hashes`` ships to the public repo carrying only
SHA-256 digests; this script reproduces the SAME normalization on both sides so
a digest match means a private name leaked into the public tree.

Normalization (identical for generate + scan):
  * lowercase; reduce each candidate to its alphanumeric "atoms"; concatenate.
  * separators (``_ - . space``) are dissolved, so ``foo-bar``, ``Foo Bar`` and
    ``fooBar`` all normalize to the same atom string ``foobar``.
  * for the tree, n-grams (1..3 atoms) are formed only WITHIN a phrase (a run of
    alnum + ``_ - . space``), so unrelated adjacent identifiers don't fuse.

Usage:
  gen:   python3 scripts/denylist_tokens.py gen  scripts/private_terms.txt > scripts/denylist.hashes
  scan:  python3 scripts/denylist_tokens.py scan <tree_dir> scripts/denylist.hashes [--reveal]
         (exit 0 = clean; exit 2 = at least one denylist hash matched)
"""
from __future__ import annotations
import hashlib
import os
import re
import sys

EXCLUDE_MARKER = "@denylist-exclude-below"
_ATOM_RE = re.compile(r"[a-z0-9]+")
# A "phrase": alnum atoms joined only by separators we dissolve. Bounds n-grams
# so they never bridge two unrelated identifiers across other punctuation.
_PHRASE_RE = re.compile(r"[a-z0-9][a-z0-9_.\- ]*[a-z0-9]|[a-z0-9]")
# Only scan text-like files; the agent bundle (.js) IS text and IS scanned.
_BINARY_EXT = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".pdf", ".zip", ".gz", ".whl",
    ".pcap", ".pcapng", ".tap", ".so", ".dylib", ".dll", ".pyc", ".bin",
}


def _sha(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


def term_hash(term: str) -> str | None:
    """Normalize a private term to its single concatenated-atoms SHA-256."""
    atoms = _ATOM_RE.findall(term.replace("\\", "").lower())
    if not atoms:
        return None
    return _sha("".join(atoms))


def load_terms(path: str) -> list[str]:
    """Enforceable terms = lines above EXCLUDE_MARKER, minus comments/blanks."""
    terms: list[str] = []
    with open(path, "r", encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if EXCLUDE_MARKER in line:
                break
            if not line or line.startswith("#"):
                continue
            terms.append(line)
    return terms


def candidate_hashes(text: str):
    """Yield (hash, atoms_str) for every 1..3-atom n-gram within each phrase."""
    for phrase in _PHRASE_RE.findall(text.lower()):
        atoms = _ATOM_RE.findall(phrase)
        for n in (1, 2, 3):
            for i in range(len(atoms) - n + 1):
                joined = "".join(atoms[i:i + n])
                yield _sha(joined), joined


def cmd_gen(terms_path: str) -> int:
    digests = {h for t in load_terms(terms_path) if (h := term_hash(t))}
    print("# friTap public denylist — name-free SHA-256 of private reveal-tokens.")
    print("# Generated by scripts/denylist_tokens.py from scripts/private_terms.txt")
    print("# (private-only). The public repo ships ONLY these digests, never the")
    print("# cleartext. Regenerate after editing private_terms.txt. See §F.")
    for d in sorted(digests):
        print(d)
    return 0


def _is_binary(path: str) -> bool:
    """Treat a file as binary (skip it) if its first 8 KiB contains a NUL byte.
    Catches extensionless blobs like the bundled tcpdump binaries that would
    otherwise decode into spurious tokens."""
    try:
        with open(path, "rb") as fh:
            return b"\x00" in fh.read(8192)
    except OSError:
        return True


def _iter_files(tree: str):
    for root, dirs, files in os.walk(tree):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__", "node_modules")]
        for name in files:
            if os.path.splitext(name)[1].lower() in _BINARY_EXT:
                continue
            path = os.path.join(root, name)
            if _is_binary(path):
                continue
            yield path


def cmd_scan(tree: str, hashes_path: str, reveal: bool) -> int:
    deny: set[str] = set()
    with open(hashes_path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                deny.add(line.split()[0])
    if not deny:
        print("[denylist] no hashes loaded — refusing to pass vacuously", file=sys.stderr)
        return 3

    hits = 0
    for path in _iter_files(tree):
        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as fh:
                text = fh.read()
        except (OSError, UnicodeError):
            continue
        seen: set[str] = set()
        for h, joined in candidate_hashes(text):
            if h in deny and h not in seen:
                seen.add(h)
                hits += 1
                rel = os.path.relpath(path, tree)
                if reveal:
                    print(f"  LEAK {rel}: matched token '{joined}' ({h[:12]}…)")
                else:
                    print(f"  LEAK {rel}: denylist digest {h[:12]}…")
    if hits:
        print(f"[denylist] {hits} reveal-token match(es) found.")
        return 2
    print("[denylist] clean — no private reveal-tokens in the tree.")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 1
    cmd = argv[1]
    if cmd == "gen" and len(argv) == 3:
        return cmd_gen(argv[2])
    if cmd == "scan" and len(argv) >= 4:
        return cmd_scan(argv[2], argv[3], "--reveal" in argv[4:])
    print(__doc__)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
