// Auto-generated from friTap/schemas/agent_messages.py
// Do NOT edit by hand. Run: python dev/generate_agent_types.py
//
// Generated by: dev/generate_agent_types.py


export interface KeylogMessage {
    contentType: "keylog";
    protocol?: string;
    keylog?: string;
}

export function isKeylogMessage(msg: unknown): msg is KeylogMessage {
    return (msg as any)?.contentType === "keylog";
}

export interface DatalogMessage {
    contentType: "datalog";
    protocol?: string;
    function?: string;
    src_addr?: number | string;
    dst_addr?: number | string;
    src_port?: number;
    dst_port?: number;
    ss_family?: string;
    ssl_session_id?: string;
}

export function isDatalogMessage(msg: unknown): msg is DatalogMessage {
    return (msg as any)?.contentType === "datalog";
}

export interface LibraryDetectedMessage {
    contentType: "library_detected";
    protocol?: string;
    library?: string;
    message?: string;
    path?: string;
}

export function isLibraryDetectedMessage(msg: unknown): msg is LibraryDetectedMessage {
    return (msg as any)?.contentType === "library_detected";
}

export interface ConsoleMessage {
    contentType: "console";
    protocol?: string;
    console?: string;
}

export function isConsoleMessage(msg: unknown): msg is ConsoleMessage {
    return (msg as any)?.contentType === "console";
}

export interface ConsoleDevMessage {
    contentType: "console_dev";
    protocol?: string;
    console_dev?: string;
}

export function isConsoleDevMessage(msg: unknown): msg is ConsoleDevMessage {
    return (msg as any)?.contentType === "console_dev";
}

export interface ConsoleDebugMessage {
    contentType: "console_debug";
    protocol?: string;
    message?: string;
    time?: string;
    file?: string | null;
    line?: number | null;
    col?: number | null;
    func?: string | null;
    level?: "debug";
}

export function isConsoleDebugMessage(msg: unknown): msg is ConsoleDebugMessage {
    return (msg as any)?.contentType === "console_debug";
}

export interface ConsoleInfoMessage {
    contentType: "console_info";
    protocol?: string;
    message?: string;
    time?: string;
    file?: string | null;
    line?: number | null;
    col?: number | null;
    func?: string | null;
    level?: "info";
}

export function isConsoleInfoMessage(msg: unknown): msg is ConsoleInfoMessage {
    return (msg as any)?.contentType === "console_info";
}

export interface ConsoleWarnMessage {
    contentType: "console_warn";
    protocol?: string;
    message?: string;
    time?: string;
    file?: string | null;
    line?: number | null;
    col?: number | null;
    func?: string | null;
    level?: "warn";
}

export function isConsoleWarnMessage(msg: unknown): msg is ConsoleWarnMessage {
    return (msg as any)?.contentType === "console_warn";
}

export interface ConsoleErrorMessage {
    contentType: "console_error";
    protocol?: string;
    message?: string;
    time?: string;
    file?: string | null;
    line?: number | null;
    col?: number | null;
    func?: string | null;
    level?: "error";
}

export function isConsoleErrorMessage(msg: unknown): msg is ConsoleErrorMessage {
    return (msg as any)?.contentType === "console_error";
}

export interface NetlogMessage {
    contentType: "netlog";
    protocol?: string;
    function?: string;
    src_addr?: number | string;
    dst_addr?: number | string;
    src_port?: number;
    dst_port?: number;
    ss_family?: string;
}

export function isNetlogMessage(msg: unknown): msg is NetlogMessage {
    return (msg as any)?.contentType === "netlog";
}

export interface SSHNewKeysMessage {
    contentType: "ssh_newkeys";
    protocol?: string;
    direction?: string;
    message?: string;
}

export function isSSHNewKeysMessage(msg: unknown): msg is SSHNewKeysMessage {
    return (msg as any)?.contentType === "ssh_newkeys";
}

export interface SSHKeyMessage {
    contentType: "ssh_key";
    protocol?: string;
    direction?: string;
    key_type?: string;
    cipher?: string;
    key_data?: string;
    key_len?: number | null;
    iv_len?: number | null;
    message?: string;
}

export function isSSHKeyMessage(msg: unknown): msg is SSHKeyMessage {
    return (msg as any)?.contentType === "ssh_key";
}

export interface IPSecChildSAKeysMessage {
    contentType: "ipsec_child_sa_keys";
    protocol?: string;
    keys?: Record<string, string>;
    message?: string;
}

export function isIPSecChildSAKeysMessage(msg: unknown): msg is IPSecChildSAKeysMessage {
    return (msg as any)?.contentType === "ipsec_child_sa_keys";
}

export interface IPSecIKEKeysMessage {
    contentType: "ipsec_ike_keys";
    protocol?: string;
    keys?: Record<string, string>;
    message?: string;
}

export function isIPSecIKEKeysMessage(msg: unknown): msg is IPSecIKEKeysMessage {
    return (msg as any)?.contentType === "ipsec_ike_keys";
}

export type AgentMessage = KeylogMessage
    | DatalogMessage
    | LibraryDetectedMessage
    | ConsoleMessage
    | ConsoleDevMessage
    | ConsoleDebugMessage
    | ConsoleInfoMessage
    | ConsoleWarnMessage
    | ConsoleErrorMessage
    | NetlogMessage
    | SSHNewKeysMessage
    | SSHKeyMessage
    | IPSecChildSAKeysMessage
    | IPSecIKEKeysMessage;
